### ISSUE TITLE
是为了实现分布式多任务吗？

### ISSUE THREAD

**Issue by jwen6118** [TianLangStudio/DataXServer#2]
怎么实现的？没看明白

**Comment by TianLangStudio** [comment]
把DataX跑在Yarn上  启一个与yarn通讯获取硬件资源的ApplicationMaster 并启动ThriftServer用于外部提交任务 ThriftServer接受到任务后会跟ApplicationMaster通讯获取必要的硬件资源用于启动DataX任务       是为了1.实现资源的统一(yarn)调度 提高资源利用率 2.实现分布式多任务提高任务并行性

**Comment by happyapple668** [comment]
那么多，并行太多的话，也是会占用太多的yarn资源~算是启动了多个dataX来达到目的？
