### ISSUE TITLE
DataX3.0 的怎么用你的这个呀 谢谢

### ISSUE THREAD

**Issue by abccaaa** [TianLangStudio/DataXServer#3]
你好，因为现在我们也想DataX On Yarn，看到您开源的  但是你的使用手册 能多写一些吗 请问现在还维护嘛

**Comment by abccaaa** [comment]
你好，因为现在我们也想DataX On Yarn，看到您开源的  但是你的使用手册 能多写一些吗 请问现在还维护嘛

**Comment by TianLangStudio** [comment]
您 好:        branch refactor  是根据datax3.0重构 的   主要修改 Engine这个类 适配3.0    全年换了工作比较忙就没维护e这个了  后面工作稳定了再继续完善
新年快乐
------------------------------------------------------------------发件人：Worry about me <notifications@github.com>发送时间：2018年2月8日(星期四) 15:31收件人：TianLangStudio/DataXServer <DataXServer@noreply.github.com>抄　送：Subscribed <subscribed@noreply.github.com>主　题：Re: [TianLangStudio/DataXServer] DataX3.0 的怎么用你的这个呀 谢谢 (#3)
你好，因为现在我们也想DataX On Yarn，看到您开源的  但是你的使用手册 能多写一些吗 请问现在还维护嘛

**Comment by happyapple668** [comment]
哇，这个厉害了，我们看看能不能基于这个改造
